### ISSUE TITLE
Localization in other languages

### ISSUE THREAD

**Issue by Cwpute** [mytja/Tarok#58]
Hello :)

I am a curious user from Fdroid that stumbled upon your game. I'd be interested in playing Tarok… if only i could understand it easily !

Would you ever be interested in having your game localized in other languages ?
I'd be happy to help!

Many opensource projects use external platforms like Weblate or Crowdin, which work really well for translators who are not accustomed to using git. As for myself, i've participated in translating several other opensource projects already, and i can help with English, and then make a full French translation as well. You could provide a first draft of enqlish translation yourself, or i could do it myself by running it through external translators, that would make for an accessible basis from which others could start translating.

**Comment by Cwpute** [comment]
Ok i didn't know English was already available in the options !

Maybe ask for the default language on the first start-up of the app ? or automatically set the default to English so as most people know where to search for language options ?
I've also seen most other apps automatically detect which language is set as default wn the device, maybe that could be done too ?

**Comment by mytja** [comment]
Hi,

> I am a curious user from Fdroid that stumbled upon your game. I'd be interested in playing Tarok… if only i could understand it easily !

That's great. Tarok is a complex game, there are so many rules and you need some time getting used to it.

> Many opensource projects use external platforms like Weblate or Crowdin, which work really well for translators who are not accustomed to using git

I was never a fan of such tools as they often spam you with pull requests and make app maintaining much more complex than it needs to be. I also never found their UI super intuitive, yet that's just my taste. At the current moment, app translations are located at https://github.com/mytja/Tarok/blob/main/tarok/lib/internationalization/languages.dart. It's a simple JSON file that needs to be edited. If you don't feel comfortable editing code, you may at any time send me the translations through GitHub Issues or my email address mytja@protonmail.com or info@palcka.si (in any kind of format).

In any case I need to manually handle the addition of new languages.

> Maybe ask for the default language on the first start-up of the app ? or automatically set the default to English so as most people know where to search for language options ?
I've also seen most other apps automatically detect which language is set as default wn the device, maybe that could be done too ?

This app was meant primarily for Slovenian market. I had to weigh between Slovene and English when selecting the fallback language. In the end, I agree would be more proper to select English as the fallback locale. Slovenian is currently selected as the language when user's device is reporting back Slovenian language setting and as a fallback locale (when the app cannot find the appropriate translation for user's device. You might have your phone set to French or en_UK and that's why it falls back to Slovenian).

In the end, I will make sure to make the fallback locale English.

**Comment by Cwpute** [comment]
I thought i had sent an answer but it didn't go through :x

I'm getting used to these rules as we speak ;)

Even if editing a simple file may not be so hard, it still requires you to get out of your way to download that file, open it in a specific editor, save it, and send it over to the maintainer. Not much by a lot of standards, but discouraging enough for many potential translators!
If Crowdin and Weblate are too complicated, i've seen much simpler tools used elsewhere. The maintainer of Snappymail has used (a small hand-crafted tool for translating)[https://snappymail.eu/translate.php] that isn't much, but still does most of the annoying work for the translator. Might be interesting to look into ?

Thanks for accepting translation through other means though, i'll be sure to find some time for the french translation in the near future!

**Comment by mytja** [comment]
Hey, so I've done something just like Snappymail creator did...

https://translate.palcka.si/

It's simple (uses questionable CSS and other styling decisions) and doesn't generate any spam PRs. It autogenerates the website on every commit, so you can be sure it'll always be up to date.

The translations should be in the end exported and sent to e-mail address info@palcka.si, my [Discord](https://discord.com/users/761599472454205531) or even through GitHub Issues if you're more comfortable with it.

I feel like this should be closed now.
