### ISSUE TITLE
Include the rulebook into the app

### ISSUE THREAD

**Issue by Cwpute** [mytja/Tarok#60]
I was searching fwr the rules for your game and fonnd this website: https://www.pagat.com/tarot/sltarok.html
But i'm not sure these are the exact rules…

Could you provide a rulebook directly integrated into the app, so that future players don't have to rely on external references ?

**Comment by mytja** [comment]
Yeah, I plan on creating a in-app tutorial sometime in the future. However, presently there're much more important features and bugs that need to be added/patched. It's also a highly complex feature to implement as it would require major changes to the UI code of the frontend/app.

**Comment by mytja** [comment]
This is done. I hope I've successfully described everything necessary to be able to play the game. I've also described the "radelci". French translation was successfully integrated, although some new strings were added in order to satisfy the the need for the rulebook.

Automatic deployment should be done within a couple of minutes, you may check the rulebook at https://palcka.si, full release might take a bit longer, but I'm targeting start of the next week as a final (v1.0.0) release.

**Comment by Cwpute** [comment]
Fantastic! This is much much easier to understand now! 😄🎉

I've seen some slovenian left out in descriptions of games of Two and One, sometimes also the word points is replaced with "točk". And some inconsistencies in the translations from one place to another that should be ironed out later (for example, Mondfang and Capture of the Mond are both used without distinction).
But this is already wonderful, and no doubt i'll manage to win a few more hands next time !

Le 10 janvier 2024 00:41:37 GMT+01:00, "Mitja Ševerkar" ***@***.***> a écrit :
